"""Add popular hashtags table

Revision ID: 284cc340b10d
Revises: c1c57d38c9bb
Create Date: 2024-07-23 21:50:38.797654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284cc340b10d'
down_revision = 'c1c57d38c9bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('popular_hash_tag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hashtags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hashtags', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.drop_table('popular_hash_tag')
    # ### end Alembic commands ###
