"""empty message

Revision ID: c1c57d38c9bb
Revises: a325c034fd98
Create Date: 2024-07-23 21:30:57.189550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c57d38c9bb'
down_revision = 'a325c034fd98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retweet_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('favorite_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweets', schema=None) as batch_op:
        batch_op.drop_column('favorite_count')
        batch_op.drop_column('retweet_count')

    # ### end Alembic commands ###
